name: Package Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Read extension version
        id: meta
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create dist directory
        run: mkdir -p dist

      - name: Package extension
        run: |
          zip -r dist/web-recall-${{ steps.meta.outputs.version }}.zip . \
            -x "node_modules/*" "dist/*" ".github/*" ".git/*"

      - name: Generate checksum
        run: shasum -a 256 dist/web-recall-${{ steps.meta.outputs.version }}.zip > dist/web-recall-${{ steps.meta.outputs.version }}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-recall-${{ steps.meta.outputs.version }}
          path: |
            dist/web-recall-${{ steps.meta.outputs.version }}.zip
            dist/web-recall-${{ steps.meta.outputs.version }}.sha256

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/web-recall-${{ steps.meta.outputs.version }}.zip
            dist/web-recall-${{ steps.meta.outputs.version }}.sha256
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
